<a href="https://colab.research.google.com/github/9bishal/Learning-Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this notebook i am going to start with the basics of the tensor using the tensorflo
We will be covering:
## 1.introdction to tensor
2.Getting information from tensor
3.Manipulation tensor
4.Tensor & Numpy
6.using @tf.function( a way to speed up your regular python function)
7.Using GPU with TPU



In [116]:
#importing the tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [117]:
# creating tensors with tf.constant()
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [118]:
#chech the no. of deimnsion
scaler.ndim

0

In [119]:
# create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [120]:
#chech the dimension of the vectro
vector.ndim

1

In [121]:
#creating a matrix(more than 1-D)
matrix=tf.constant([[10,7],
 [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [122]:
matrix.ndim

2

In [123]:
# create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]], dtype=tf.float16) #specify the dtype


In [124]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [125]:
#no. of dimension
another_matrix.ndim

2

In [126]:
#creating a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [12,13,14]]])
tensor

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [12, 13, 14]]], dtype=int32)>

In [127]:
tensor.ndim

3

what we've created so far
*Scaler: a single number
*Vectro: a number with directional_link
*matrix: a 2-D array of a number
*Tensor: an n-dimensional array if numbers

Creating the tensor with the Tensor

In [128]:
#creating the same tensor with the variable
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7],dtype=16)
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=quint16, numpy=array([10,  7], dtype=uint16)>)

In [129]:
# Lets try the .assign() to changable tensor
changable_tensor[0].assign(10)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [130]:
# Lets try the .assign() to unchangable tensor
# unchangable_tensor[0].assign(10)
# unchangable_tensor

# Creating the Random Tensor
Random Teansor mean creating the random no. of dimension

In [131]:
#create two random(but the same) tenso
random_1=tf.random.Generator.from_seed(42) #set seed for the reproductibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2, random_2==random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the elements in a tensor

In [132]:
#shufle a tensor( valuable when you want to shuffle a data so that )
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
not_shuffled.ndim

2

In [133]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [134]:
#shuffle our not_shuffled tensor
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [135]:
tf.random.shuffle(not_shuffled, seed=42) #local level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [136]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

###Other ways to make a Tensor

In [137]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [138]:
#creating a tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

###we can also turn numpy arrays as Tensor


In [139]:
#The main difference between tensor and a numpy array is that we can run tensor much more faster in GPU
import numpy as np
numpy_A= np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [140]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [141]:
B=tf.constant(numpy_A)

A=tf.constant(numpy_A, shape=(2,3,4)) #changing the shape of the Tensor

A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

###Getting more information from Tensor

*Shape
*Rank
*Axis or dimension
*Size

In [142]:
#Create a rank 4 tensor(4 dimension)
rank_4_dimension=tf.zeros(shape=[2,3,4,5])
rank_4_dimension

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [143]:
rank_4_dimension[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [144]:
rank_4_dimension[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [145]:
rank_4_dimension.shape, rank_4_dimension.ndim, tf.size(rank_4_dimension)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

###Get various Attributes of our Tensor

In [146]:
print("DataType of every elements:", rank_4_dimension.dtype)
print("Number of Dimension (Rank):",rank_4_dimension.ndim)
print("Shape of Tensor:", rank_4_dimension.shape)
print("Elements along the 0 axies:",rank_4_dimension.shape[0])
print("Elements along the last axis:", rank_4_dimension.shape[-1])
print("Total number of Elements in our Tensor:", tf.size(rank_4_dimension).numpy())

DataType of every elements: <dtype: 'float32'>
Number of Dimension (Rank): 4
Shape of Tensor: (2, 3, 4, 5)
Elements along the 0 axies: 2
Elements along the last axis: 5
Total number of Elements in our Tensor: 120


#Indexing Tensors
###Tensor can be indexed as python list

In [147]:
#getting the first 2 elements of each Dimensio
rank_4_dimension[:2,:2,:4,:5] #

<tf.Tensor: shape=(2, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [148]:
#Get the first element from each of the index except the final one
rank_4_dimension[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [149]:
#Create a rank 2 tensor(2-Dimensio)
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [150]:
#Last element of the row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [151]:
#Adding extra dimension
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [152]:
#Adding extra dimension by another method
rank_3_tensor=rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [153]:
#Adding extra dimension by another method
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [154]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [155]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

# 23. Manipulating tensors with basic operations

## Basic Operation

### '+'-','*','/'

In [156]:
tensor=tf.constant([[10,7],[3,4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [157]:
#original Tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [158]:
#multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [159]:
#Substraction also works
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [160]:
#we can use the tensorflow built function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [161]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [162]:
tf.math.add(
    tensor, 10, name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

# 24. Matrix multiplication with tensors part 1

In Machine Learning, matrix multiplication is one of the common tesor operation

In [163]:
c = tf.matmul(tensor, tensor+10)
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[291, 268],
       [112, 107]], dtype=int32)>

In [164]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [165]:
tensor1=tf.constant([1,2,3,4,5,6,7,8,9], shape=[3,3])
tensor2=tf.constant([1,2,3,4,5,6], shape=[3,2])
mul_result=tf.matmul(tensor1, tensor2)
mul_result


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]], dtype=int32)>

Another way for the matrix Multiplication

In [166]:
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]], dtype=int32)>

# 25. Matrix multiplication with tensors part 2

In [167]:
tensor=tf.constant([[1,2,3],
                   [4,5,6]])
tf.reshape(tensor, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [168]:
tf.reshape(tensor, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [169]:
tensor.shape

TensorShape([2, 3])

In [170]:
tf.transpose(tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [171]:
tf.matmul(tf.transpose(tensor),tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

# 26. Matrix multiplication with tensors part 3

###We can do the matrix multiplication using the:
###1.tf.matmul()
###2.tf.tensordot()

In [172]:
#performing the dot product on two matrix
tf.tensordot(tf.transpose(tensor), tensor, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

In [173]:
#with the transposed
tf.matmul(tensor, tf.transpose(tensor))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [174]:
#with the reshaped
tf.matmul(tensor, tf.reshape(tensor, shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [175]:
tf.tensordot(tensor, tf.transpose(tensor), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [176]:
#with the reshaped
tf.tensordot(tensor, tf.reshape(tensor, shape=(3,2)), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

#27. Changing the datatype of tensors

In [177]:
a=tf.constant([7,10])

In [178]:
b=tf.cast(a, dtype=tf.float16)
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [179]:
c=tf.cast(b, dtype=tf.int16)
c

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>

# 28. Tensor aggregation (finding the min, max, mean & more)

Agrgregating tensors=condensing them from multiple values dowm to a smaller amount of values

In [180]:
#getting the absoulute valuess
d=tf.constant([-7,10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [181]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregaations:
*get the minimum
*get the maximum
*get the mean of a tensor
*get the sum of a tensor

In [182]:
#creat a random tensor with the values between 0 and 100 of size 50
e=tf.constant(np.random.randint(0,100, size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([57, 36, 13, 35, 99, 96, 40, 50, 92, 23, 67, 10, 66, 92, 35, 32, 34,
       98, 55, 60, 42, 23, 65, 76, 83, 15, 46,  0, 49, 89, 23, 78, 85, 32,
       27, 28, 94, 21, 19, 52, 68, 43, 41, 23, 72, 68, 13, 65, 95, 61])>

In [183]:
tf.size(e), e.shape, e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [184]:
#find the minimum

tf.reduce_min(e)


<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [185]:
np.min(e)

0

In [186]:
#find the maximum

tf.reduce_max(e)


<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [187]:
np.max(e)

99

In [188]:
#find the mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [189]:
np.mean(e)

51.72

In [190]:
#finding the sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2586>

In [191]:
np.sum(e)

2586

# 29. Tensor troubleshooting example (updating tensor datatypes)

In [192]:
#finding the variance
import tensorflow_probability as tfp
var=tfp.stats.variance(e, sample_axis=0)
var

<tf.Tensor: shape=(), dtype=int64, numpy=751>

To claculate the standard deviation, we need to chnage the int data type to float

In [193]:
#finding the standard division / integeer must be real or complex
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.4000301361084>

# 30. Finding the positional minimum and maximum of a tensor (argmin and argmax)

In [194]:
tf.random.set_seed(42)

f=tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [195]:
#finding the positional maximum(index)
tf.math.argmax(f).numpy(), tf.argmax(f).numpy()

(42, 42)

In [196]:
#finding the value of the largest vales's index
f[tf.argmax(f)].numpy()

0.9671384

In [197]:
#finding the max value
tf.reduce_max(f).numpy()

0.9671384

In [198]:
#checking for the equality
f[tf.argmax(f)].numpy()==tf.reduce_max(f).numpy()

True

In [199]:
#finding the positional minimum(index)
tf.math.argmin(f).numpy(), tf.argmin(f).numpy()

(16, 16)

In [200]:
#finding the minimum value via index
f[tf.argmin(f)].numpy()

0.009463668

In [201]:
#finding the min value
tf.reduce_min(f).numpy()

0.009463668

# 31. Squeezing a tensor (removing all 1-dimension axes)

In [202]:
#create a tensor to get started
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [203]:
g_squeezed=tf.squeeze(g)
g_squeezed, g_squeezed.shape #Removes dimensions of size 1 from the shape of a tensor.

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One Hot enCoding

In [204]:
indices=tf.constant([0,1,2]) #we even can create n-dimension
depth=3
tf.one_hot(indices, depth) # depth will expand the no. of columns(axix=1)| row(axis=0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [205]:
indices=tf.constant([0,1,2]) #we even can create n-dimension
depth=4
tf.one_hot(indices, depth, on_value="I am 1", off_value="I am 0", axis=1) # depth will expand the no. of columns

<tf.Tensor: shape=(3, 4), dtype=string, numpy=
array([[b'I am 1', b'I am 0', b'I am 0', b'I am 0'],
       [b'I am 0', b'I am 1', b'I am 0', b'I am 0'],
       [b'I am 0', b'I am 0', b'I am 1', b'I am 0']], dtype=object)>

In [206]:
indices=tf.constant([0,1,2]) #we even can create n-dimension
depth=4
tf.one_hot(indices, depth, on_value="I am 1", off_value="I am 0", axis=0) # depth will expand the no. of columns

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'I am 1', b'I am 0', b'I am 0'],
       [b'I am 0', b'I am 1', b'I am 0'],
       [b'I am 0', b'I am 0', b'I am 1'],
       [b'I am 0', b'I am 0', b'I am 0']], dtype=object)>

In [207]:
#Square root
tf.sqrt(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)>

In [208]:
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [209]:
#log operation (accepts dtype of float32 bits)
tf.math.log(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.       , 0.6931472, 1.0986123],
       [1.3862944, 1.609438 , 1.7917595]], dtype=float32)>

In [210]:
x = tf.constant([0, 0.5, 1, 5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

# Tensors and Numpy

TensorFlow interacts beautifully with Numpy

In [211]:
#create a tensor directly from the numpy array
j=tf.constant(np.array([3.,7.,10.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [212]:
np.array(j)

array([ 3.,  7., 10.])

In [213]:
#converting to the numpy
j.numpy()

array([ 3.,  7., 10.])

In [214]:
type(j.numpy())

numpy.ndarray

In [215]:
#the default type of each are slightly different
numpy_j=tf.constant(np.array([3.,7.,10.]))
tensor_j=tf.constant([3.,7.,10.])
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)

# 35. Making sure our tensor operations run really fast on GPUs

## finding the access to GPU

In [4]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [217]:
tf.config.list_physical_devices('GPU')

[]

In [5]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [6]:
!nvidia-smi

Sat Feb  1 15:58:15 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----