<a href="https://colab.research.google.com/github/9bishal/Learning-Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this notebook i am going to start with the basics of the tensor using the tensorflo
We will be covering:
## 1.introdction to tensor
2.Getting information from tensor
3.Manipulation tensor
4.Tensor & Numpy
6.using @tf.function( a way to speed up your regular python function)
7.Using GPU with TPU



In [114]:
#importing the tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [115]:
# creating tensors with tf.constant()
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [116]:
#chech the no. of deimnsion
scaler.ndim

0

In [117]:
# create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [118]:
#chech the dimension of the vectro
vector.ndim

1

In [119]:
#creating a matrix(more than 1-D)
matrix=tf.constant([[10,7],
 [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [120]:
matrix.ndim

2

In [121]:
# create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]], dtype=tf.float16) #specify the dtype


In [122]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [123]:
#no. of dimension
another_matrix.ndim

2

In [124]:
#creating a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [12,13,14]]])
tensor

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [12, 13, 14]]], dtype=int32)>

In [125]:
tensor.ndim

3

what we've created so far
*Scaler: a single number
*Vectro: a number with directional_link
*matrix: a 2-D array of a number
*Tensor: an n-dimensional array if numbers

Creating the tensor with the Tensor

In [126]:
#creating the same tensor with the variable
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7],dtype=16)
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=quint16, numpy=array([10,  7], dtype=uint16)>)

In [127]:
# Lets try the .assign() to changable tensor
changable_tensor[0].assign(10)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [128]:
# Lets try the .assign() to unchangable tensor
# unchangable_tensor[0].assign(10)
# unchangable_tensor

# Creating the Random Tensor
Random Teansor mean creating the random no. of dimension

In [129]:
#create two random(but the same) tenso
random_1=tf.random.Generator.from_seed(42) #set seed for the reproductibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2, random_2==random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the elements in a tensor

In [130]:
#shufle a tensor( valuable when you want to shuffle a data so that )
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
not_shuffled.ndim

2

In [131]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [132]:
#shuffle our not_shuffled tensor
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [133]:
tf.random.shuffle(not_shuffled, seed=42) #local level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [134]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

###Other ways to make a Tensor

In [135]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [136]:
#creating a tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

###we can also turn numpy arrays as Tensor


In [137]:
#The main difference between tensor and a numpy array is that we can run tensor much more faster in GPU
import numpy as np
numpy_A= np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [138]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [139]:
B=tf.constant(numpy_A)

A=tf.constant(numpy_A, shape=(2,3,4)) #changing the shape of the Tensor

A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

###Getting more information from Tensor

*Shape
*Rank
*Axis or dimension
*Size

In [140]:
#Create a rank 4 tensor(4 dimension)
rank_4_dimension=tf.zeros(shape=[2,3,4,5])
rank_4_dimension

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [141]:
rank_4_dimension[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [142]:
rank_4_dimension[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [143]:
rank_4_dimension.shape, rank_4_dimension.ndim, tf.size(rank_4_dimension)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

###Get various Attributes of our Tensor

In [144]:
print("DataType of every elements:", rank_4_dimension.dtype)
print("Number of Dimension (Rank):",rank_4_dimension.ndim)
print("Shape of Tensor:", rank_4_dimension.shape)
print("Elements along the 0 axies:",rank_4_dimension.shape[0])
print("Elements along the last axis:", rank_4_dimension.shape[-1])
print("Total number of Elements in our Tensor:", tf.size(rank_4_dimension).numpy())

DataType of every elements: <dtype: 'float32'>
Number of Dimension (Rank): 4
Shape of Tensor: (2, 3, 4, 5)
Elements along the 0 axies: 2
Elements along the last axis: 5
Total number of Elements in our Tensor: 120


#Indexing Tensors
###Tensor can be indexed as python list

In [145]:
#getting the first 2 elements of each Dimensio
rank_4_dimension[:2,:2,:4,:5] #

<tf.Tensor: shape=(2, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [146]:
#Get the first element from each of the index except the final one
rank_4_dimension[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [147]:
#Create a rank 2 tensor(2-Dimensio)
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [148]:
#Last element of the row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [149]:
#Adding extra dimension
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [150]:
#Adding extra dimension by another method
rank_3_tensor=rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [151]:
#Adding extra dimension by another method
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [152]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [153]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

# 23. Manipulating tensors with basic operations

## Basic Operation

### '+'-','*','/'

In [154]:
tensor=tf.constant([[10,7],[3,4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [155]:
#original Tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [156]:
#multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [157]:
#Substraction also works
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [158]:
#we can use the tensorflow built function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [159]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [160]:
tf.math.add(
    tensor, 10, name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

# 24. Matrix multiplication with tensors part 1

In Machine Learning, matrix multiplication is one of the common tesor operation

In [161]:
c = tf.matmul(tensor, tensor+10)
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[291, 268],
       [112, 107]], dtype=int32)>

In [162]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [163]:
tensor1=tf.constant([1,2,3,4,5,6,7,8,9], shape=[3,3])
tensor2=tf.constant([1,2,3,4,5,6], shape=[3,2])
mul_result=tf.matmul(tensor1, tensor2)
mul_result


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]], dtype=int32)>

Another way for the matrix Multiplication

In [164]:
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]], dtype=int32)>

# 25. Matrix multiplication with tensors part 2

In [169]:
tensor=tf.constant([[1,2,3],
                   [4,5,6]])
tf.reshape(tensor, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [171]:
tf.reshape(tensor, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [173]:
tensor.shape

TensorShape([2, 3])