<a href="https://colab.research.google.com/github/9bishal/Learning-Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this notebook i am going to start with the basics of the tensor using the tensorflo
We will be covering:
## 1.introdction to tensor
2.Getting information from tensor
3.Manipulation tensor
4.Tensor & Numpy
6.using @tf.function( a way to speed up your regular python function)
7.Using GPU with TPU



In [1]:
#importing the tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [2]:
# creating tensors with tf.constant()
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#chech the no. of deimnsion
scaler.ndim

0

In [4]:
# create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#chech the dimension of the vectro
vector.ndim

1

In [6]:
#creating a matrix(more than 1-D)
matrix=tf.constant([[10,7],
 [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]], dtype=tf.float16) #specify the dtype


In [9]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
#no. of dimension
another_matrix.ndim

2

In [11]:
#creating a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [12,13,14]]])
tensor

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [12, 13, 14]]], dtype=int32)>

In [12]:
tensor.ndim

3

what we've created so far
*Scaler: a single number
*Vectro: a number with directional_link
*matrix: a 2-D array of a number
*Tensor: an n-dimensional array if numbers

Creating the tensor with the Tensor

In [13]:
#creating the same tensor with the variable
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7],dtype=16)
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=quint16, numpy=array([10,  7], dtype=uint16)>)

In [14]:
# Lets try the .assign() to changable tensor
changable_tensor[0].assign(10)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [15]:
# Lets try the .assign() to unchangable tensor
# unchangable_tensor[0].assign(10)
# unchangable_tensor

# Creating the Random Tensor
Random Teansor mean creating the random no. of dimension

In [16]:
#create two random(but the same) tenso
random_1=tf.random.Generator.from_seed(42) #set seed for the reproductibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1,random_2, random_2==random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the elements in a tensor

In [17]:
#shufle a tensor( valuable when you want to shuffle a data so that )
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
not_shuffled.ndim

2

In [18]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
#shuffle our not_shuffled tensor
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [20]:
tf.random.shuffle(not_shuffled, seed=42) #local level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

###Other ways to make a Tensor

In [22]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
#creating a tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

###we can also turn numpy arrays as Tensor


In [24]:
#The main difference between tensor and a numpy array is that we can run tensor much more faster in GPU
import numpy as np
numpy_A= np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [25]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [26]:
B=tf.constant(numpy_A)

A=tf.constant(numpy_A, shape=(2,3,4)) #changing the shape of the Tensor

A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

###Getting more information from Tensor

*Shape
*Rank
*Axis or dimension
*Size

In [27]:
#Create a rank 4 tensor(4 dimension)
rank_4_dimension=tf.zeros(shape=[2,3,4,5])
rank_4_dimension

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_dimension[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [29]:
rank_4_dimension[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [30]:
rank_4_dimension.shape, rank_4_dimension.ndim, tf.size(rank_4_dimension)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

###Get various Attributes of our Tensor

In [31]:
print("DataType of every elements:", rank_4_dimension.dtype)
print("Number of Dimension (Rank):",rank_4_dimension.ndim)
print("Shape of Tensor:", rank_4_dimension.shape)
print("Elements along the 0 axies:",rank_4_dimension.shape[0])
print("Elements along the last axis:", rank_4_dimension.shape[-1])
print("Total number of Elements in our Tensor:", tf.size(rank_4_dimension).numpy())

DataType of every elements: <dtype: 'float32'>
Number of Dimension (Rank): 4
Shape of Tensor: (2, 3, 4, 5)
Elements along the 0 axies: 2
Elements along the last axis: 5
Total number of Elements in our Tensor: 120


#Indexing Tensors
###Tensor can be indexed as python list

In [32]:
#getting the first 2 elements of each Dimensio
rank_4_dimension[:2,:2,:4,:5] #

<tf.Tensor: shape=(2, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
#Get the first element from each of the index except the final one
rank_4_dimension[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [34]:
#Create a rank 2 tensor(2-Dimensio)
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [35]:
#Last element of the row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [36]:
#Adding extra dimension
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [37]:
#Adding extra dimension by another method
rank_3_tensor=rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [38]:
#Adding extra dimension by another method
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [39]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [40]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

# 23. Manipulating tensors with basic operations

## Basic Operation

### '+'-','*','/'

In [41]:
tensor=tf.constant([[10,7],[3,4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [42]:
#original Tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [43]:
#multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [44]:
#Substraction also works
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [45]:
#we can use the tensorflow built function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [46]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [47]:
tf.math.add(
    tensor, 10, name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

# 24. Matrix multiplication with tensors part 1

In Machine Learning, matrix multiplication is one of the common tesor operation

In [48]:
c = tf.matmul(tensor, tensor+10)
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[291, 268],
       [112, 107]], dtype=int32)>

In [49]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [50]:
tensor1=tf.constant([1,2,3,4,5,6,7,8,9], shape=[3,3])
tensor2=tf.constant([1,2,3,4,5,6], shape=[3,2])
mul_result=tf.matmul(tensor1, tensor2)
mul_result


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]], dtype=int32)>

Another way for the matrix Multiplication

In [51]:
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]], dtype=int32)>

# 25. Matrix multiplication with tensors part 2

In [52]:
tensor=tf.constant([[1,2,3],
                   [4,5,6]])
tf.reshape(tensor, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [53]:
tf.reshape(tensor, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [54]:
tensor.shape

TensorShape([2, 3])

In [55]:
tf.transpose(tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [56]:
tf.matmul(tf.transpose(tensor),tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

# 26. Matrix multiplication with tensors part 3

###We can do the matrix multiplication using the:
###1.tf.matmul()
###2.tf.tensordot()

In [57]:
#performing the dot product on two matrix
tf.tensordot(tf.transpose(tensor), tensor, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

In [58]:
#with the transposed
tf.matmul(tensor, tf.transpose(tensor))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [67]:
#with the reshaped
tf.matmul(tensor, tf.reshape(tensor, shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [68]:
tf.tensordot(tensor, tf.transpose(tensor), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [69]:
#with the reshaped
tf.tensordot(tensor, tf.reshape(tensor, shape=(3,2)), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

#27. Changing the datatype of tensors

In [70]:
a=tf.constant([7,10])

In [71]:
b=tf.cast(a, dtype=tf.float16)
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [72]:
c=tf.cast(b, dtype=tf.int16)
c

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>

# 28. Tensor aggregation (finding the min, max, mean & more)

Agrgregating tensors=condensing them from multiple values dowm to a smaller amount of values

In [75]:
#getting the absoulute valuess
d=tf.constant([-7,10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [76]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregaations:
*get the minimum
*get the maximum
*get the mean of a tensor
*get the sum of a tensor

In [77]:
#creat a random tensor with the values between 0 and 100 of size 50
e=tf.constant(np.random.randint(0,100, size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([22, 87, 94, 53, 97, 30, 28,  9, 93, 17, 36, 77, 81, 97, 50, 20, 68,
       31, 67, 68, 51, 89, 98, 12, 77, 51, 48,  4, 98, 11, 85, 83, 69, 33,
       57, 10, 14, 64, 33, 93, 83, 91, 34, 30, 71, 75, 13, 64,  9, 41])>

In [78]:
tf.size(e), e.shape, e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [84]:
#find the minimum

tf.reduce_min(e)


<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [82]:
np.min(e)

4

In [85]:
#find the maximum

tf.reduce_max(e)


<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [86]:
np.max(e)

98

In [87]:
#find the mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [88]:
np.mean(e)

54.32

In [89]:
#finding the sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2716>

In [90]:
np.sum(e)

2716

# 29. Tensor troubleshooting example (updating tensor datatypes)

In [104]:
#finding the variance
import tensorflow_probability as tfp
var=tfp.stats.variance(e, sample_axis=0)
var

<tf.Tensor: shape=(), dtype=int64, numpy=903>

To claculate the standard deviation, we need to chnage the int data type to float

In [103]:
#finding the standard division / integeer must be real or complex
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.058902740478516>

# 30. Finding the positional minimum and maximum of a tensor (argmin and argmax)

In [108]:
tf.random.set_seed(42)

f=tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [115]:
#finding the positional maximum(index)
tf.math.argmax(f).numpy(), tf.argmax(f).numpy()

(42, 42)

In [116]:
#finding the value of the largest vales's index
f[tf.argmax(f)].numpy()

0.9671384

In [118]:
#finding the max value
tf.reduce_max(f).numpy()

0.9671384

In [122]:
#checking for the equality
f[tf.argmax(f)].numpy()==tf.reduce_max(f).numpy()

True

In [119]:
#finding the positional minimum(index)
tf.math.argmin(f).numpy(), tf.argmin(f).numpy()

(16, 16)

In [120]:
#finding the minimum value via index
f[tf.argmin(f)].numpy()

0.009463668

In [121]:
#finding the min value
tf.reduce_min(f).numpy()

0.009463668

# 31. Squeezing a tensor (removing all 1-dimension axes)

In [126]:
#create a tensor to get started
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [127]:
g_squeezed=tf.squeeze(g)
g_squeezed, g_squeezed.shape #Removes dimensions of size 1 from the shape of a tensor.

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))